name: Deployment

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean remote directory
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf ~/mock.dcism.org/*

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "*"
          exclude: "./node_modules, ./.git*, ./.github, /etc, /lib"
          target: "~/mock.dcism.org/"
          overwrite: true

      - name: Setup and build on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/mock.dcism.org
            echo 'DirectoryIndex disabled' > .htaccess
            echo '' >> .htaccess
            echo 'RewriteEngine on' >> .htaccess
            echo '' >> .htaccess
            echo 'RewriteCond %{SERVER_PORT} 80' >> .htaccess
            echo 'RewriteRule ^.*$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]' >> .htaccess
            echo '' >> .htaccess
            echo 'RewriteRule (.*) http://127.0.0.1:8888%{REQUEST_URI} [P,L]' >> .htaccess

            npm install
            npm run build
            npx pm2 delete mock || true
            npx pm2 start npm --name 'mock' -- start
