name: Deployment

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1: Kill PM2 and delete old files
      - name: Clean up remote server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pm2 kill || true
            rm -rf ~/mock.dcism.org/*

      # Step 2: Upload new files
      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "*"
          exclude: "./node_modules, ./.git*, ./.github, /etc, /lib"
          target: "~/mock.dcism.org/"
          overwrite: true

      # Step 3: Create .htaccess and deploy
      - name: Setup and build on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/mock.dcism.org
            cat <<EOF > .htaccess
            DirectoryIndex disabled

            RewriteEngine on

            RewriteCond %{SERVER_PORT} 80
            RewriteRule ^.*$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

            RewriteRule (.*) http://127.0.0.1:8888%{REQUEST_URI} [P,L]
            EOF

            npm install
            npm run build
            npx pm2 start npm --name 'mock' -- start
